services:
  - type: web
    name: gandalf
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gandalf-db
          property: connectionString
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: WORKFLOW_FILE
        sync: false
      - key: LD_API_KEY
        sync: false
      - key: LD_PROJECT_KEY
        sync: false
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: gandalf-db
    plan: free
